version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - deps/go
    groups:
      go-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      go-version-updates:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - deps/npm
    groups:
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      npm-version-updates:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - deps/github-actions
    groups:
      gha-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      gha-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
