vulnerability-check: true
comment-summary-in-pr: always
fail-on-severity: high
license-check: true
allow-dependencies-licenses:
  - pkg:golang/github.com/apparentlymart/go-textseg/v15
  - pkg:golang/golang.org/x/mod
  - pkg:golang/golang.org/x/tools
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - MPL-2.0
