FROM node:24-bookworm-slim@sha256:03eae3ef7e88a9de535496fb488d67e02b9d96a063a8967bae657744ecd513f2 AS builder
WORKDIR /web

COPY web/package*.json ./
RUN npm ci

COPY web ./

ARG VITE_IDENTRAIL_API_URL
ENV VITE_IDENTRAIL_API_URL=${VITE_IDENTRAIL_API_URL}

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.27-alpine@sha256:65e3e85dbaed8ba248841d9d58a899b6197106c23cb0ff1a132b7bfe0547e4c0
ARG NGINX_CONF=default.conf
COPY deploy/docker/nginx/${NGINX_CONF} /etc/nginx/conf.d/default.conf
COPY --from=builder /web/dist /usr/share/nginx/html

EXPOSE 8080
