package telemetry

import "github.com/prometheus/client_golang/prometheus"

// Metrics bundles Prometheus instruments used by API and workers.
type Metrics struct {
	ScanRunsTotal                          prometheus.Counter
	ScanSuccessTotal                       prometheus.Counter
	ScanFailureTotal                       prometheus.Counter
	ScanPartialTotal                       prometheus.Counter
	ScanInFlight                           prometheus.Gauge
	ScanDurationMS                         prometheus.Histogram
	FindingsGenerated                      prometheus.Counter
	RepoScanRunsTotal                      prometheus.Counter
	RepoScanFailureTotal                   prometheus.Counter
	RepoScanDurationMS                     prometheus.Histogram
	QueueDepth                             *prometheus.GaugeVec
	WorkerJobsTotal                        *prometheus.CounterVec
	WorkerRequeuesTotal                    *prometheus.CounterVec
	WorkerDeadLettersTotal                 *prometheus.CounterVec
	WorkerRetriesTotal                     *prometheus.CounterVec
	AuthzPolicyShadowEvaluationsTotal      prometheus.Counter
	AuthzPolicyShadowDivergencesTotal      prometheus.Counter
	AuthzPolicyShadowEvaluationErrorsTotal prometheus.Counter
	AuthzPolicyShadowDivergenceRate        prometheus.Gauge
	AuthzPolicyRollbacksTotal              prometheus.Counter
	AuthzPolicyDecisionsByVersionTotal     *prometheus.CounterVec
}

// NewMetrics initializes a dedicated registry-safe instrument set.
func NewMetrics() *Metrics {
	return &Metrics{
		ScanRunsTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "runs_total",
			Help:      "Total number of scan runs.",
		}),
		ScanSuccessTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "success_total",
			Help:      "Total number of successful scan runs.",
		}),
		ScanFailureTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "failure_total",
			Help:      "Total number of failed scan run attempts.",
		}),
		ScanPartialTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "partial_total",
			Help:      "Total number of scans completed with partial source errors.",
		}),
		ScanInFlight: prometheus.NewGauge(prometheus.GaugeOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "in_flight",
			Help:      "Current number of in-flight scan triggers.",
		}),
		ScanDurationMS: prometheus.NewHistogram(prometheus.HistogramOpts{
			Namespace: "identrail",
			Subsystem: "scan",
			Name:      "duration_milliseconds",
			Help:      "Duration of scans in milliseconds.",
			Buckets:   []float64{100, 250, 500, 1000, 2000, 5000, 10000},
		}),
		FindingsGenerated: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "analysis",
			Name:      "findings_generated_total",
			Help:      "Number of findings generated by the risk engine.",
		}),
		RepoScanRunsTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "repo_scan",
			Name:      "runs_total",
			Help:      "Total number of repository exposure scans.",
		}),
		RepoScanFailureTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "repo_scan",
			Name:      "failure_total",
			Help:      "Total number of failed repository exposure scans.",
		}),
		RepoScanDurationMS: prometheus.NewHistogram(prometheus.HistogramOpts{
			Namespace: "identrail",
			Subsystem: "repo_scan",
			Name:      "duration_milliseconds",
			Help:      "Duration of repository exposure scans in milliseconds.",
			Buckets:   []float64{100, 250, 500, 1000, 2000, 5000, 10000, 30000, 60000},
		}),
		QueueDepth: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: "identrail",
			Subsystem: "queue",
			Name:      "depth",
			Help:      "Current queued job depth by bounded queue name.",
		}, []string{"queue"}),
		WorkerJobsTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "worker",
			Name:      "jobs_total",
			Help:      "Total worker queue jobs processed by bounded queue name and outcome.",
		}, []string{"queue", "outcome"}),
		WorkerRequeuesTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "worker",
			Name:      "requeues_total",
			Help:      "Total queued jobs requeued by bounded queue name.",
		}, []string{"queue"}),
		WorkerDeadLettersTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "worker",
			Name:      "dead_letters_total",
			Help:      "Total worker jobs or scheduled triggers that exhausted retries by bounded runner name.",
		}, []string{"runner"}),
		WorkerRetriesTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "worker",
			Name:      "retries_total",
			Help:      "Total worker retryable failures by bounded runner name.",
		}, []string{"runner"}),
		AuthzPolicyShadowEvaluationsTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "authz_policy_rollout",
			Name:      "shadow_evaluations_total",
			Help:      "Total number of shadow candidate policy evaluations.",
		}),
		AuthzPolicyShadowDivergencesTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "authz_policy_rollout",
			Name:      "shadow_divergences_total",
			Help:      "Total number of shadow evaluations where candidate decision diverged from enforced decision.",
		}),
		AuthzPolicyShadowEvaluationErrorsTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "authz_policy_rollout",
			Name:      "shadow_evaluation_errors_total",
			Help:      "Total number of shadow candidate evaluations that failed.",
		}),
		AuthzPolicyShadowDivergenceRate: prometheus.NewGauge(prometheus.GaugeOpts{
			Namespace: "identrail",
			Subsystem: "authz_policy_rollout",
			Name:      "shadow_divergence_rate",
			Help:      "Observed shadow divergence rate (divergences/evaluations).",
		}),
		AuthzPolicyRollbacksTotal: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "authz_policy_rollout",
			Name:      "rollbacks_total",
			Help:      "Total number of explicit policy rollback operations.",
		}),
		AuthzPolicyDecisionsByVersionTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: "identrail",
			Subsystem: "authz_policy",
			Name:      "decisions_by_version_total",
			Help:      "Total policy decisions grouped by policy version and decision metadata.",
		}, []string{"policy_set_id", "policy_version", "policy_source", "rollout_mode", "allowed"}),
	}
}
