apiVersion: apps/v1
kind: Deployment
metadata:
  name: identrail-worker
  namespace: identrail
  labels:
    app: identrail-worker
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: identrail-worker
  template:
    metadata:
      labels:
        app: identrail-worker
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: ghcr.io/identrail/identrail-worker:v1.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: identrail-config
            - secretRef:
                name: identrail-secrets
          env:
            - name: IDENTRAIL_RUN_MIGRATIONS
              value: "false"
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/identrail
                - --healthcheck
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/identrail
                - --healthcheck
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            capabilities:
              drop:
                - ALL
