name: Actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: go.mod
          cache: false

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.12

      - name: Run actionlint
        run: '"$(go env GOPATH)/bin/actionlint" -shellcheck='
